export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_MOVIES_DETAILS = "FETCH_MOVIES_DETAILS"

// Initial props actions
export const INITIAL_POPULAR_MOVIES = "INITIAL_POPULAR_MOVIES"
